name: meetng_bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - alembic==1.15.1
      - antlr4-python3-runtime==4.9.3
      - asteroid-filterbanks==0.4.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorlog==6.9.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - docopt==0.6.2
      - einops==0.8.1
      - exceptiongroup==1.2.2
      - ffmpeg==1.4
      - ffmpeg-python==0.2.0
      - filelock==3.18.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - future==1.0.0
      - greenlet==3.1.1
      - h11==0.14.0
      - huggingface-hub==0.29.3
      - HyperPyYAML==1.2.2
      - idna==3.10
      - Jinja2==3.1.6
      - joblib==1.4.2
      - julius==0.2.7
      - kiwisolver==1.4.8
      - lightning==2.5.0.post0
      - lightning-utilities==0.14.1
      - llvmlite==0.44.0
      - Mako==1.3.9
      - markdown-it-py==3.0.0
      - MarkupSafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==2.1.3
      - openai-whisper==20240930
      - optuna==4.2.1
      - pandas==2.2.3
      - pillow==11.1.0
      - primePy==1.3
      - propcache==0.3.0
      - protobuf==6.30.1
      - pyannote.audio==3.3.2
      - pyannote.core==5.0.0
      - pyannote.database==5.1.3
      - pyannote.metrics==3.2.1
      - pyannote.pipeline==3.0.1
      - PyAudio==0.2.14
      - pydub==0.25.1
      - Pygments==2.19.1
      - pyparsing==3.2.1
      - PySocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytorch-lightning==2.5.0.post0
      - pytorch-metric-learning==2.8.1
      - pytz==2025.1
      - PyYAML==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - ruamel.yaml==0.18.10
      - ruamel.yaml.clib==0.2.12
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - selenium==4.29.0
      - semver==3.0.4
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sounddevice==0.5.1
      - soundfile==0.13.1
      - speechbrain==1.0.2
      - SQLAlchemy==2.0.39
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboardX==2.6.2.2
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - torch-audiomentations==0.12.0
      - torch_pitch_shift==1.2.5
      - torchmetrics==1.6.3
      - tqdm==4.67.1
      - trio==0.29.0
      - trio-websocket==0.12.2
      - triton==3.2.0
      - typer==0.15.2
      - typing_extensions==4.12.2
      - tzdata==2025.1
      - undetected-chromedriver==3.5.5
      - urllib3==2.3.0
      - webdriver-manager==4.0.2
      - websocket-client==1.8.0
      - websockets==15.0.1
      - wsproto==1.2.0
      - yarl==1.18.3
